
about :

  name : "wFilesArchive"
  description : "Experimental. Several classes to reflect changes of files on dependent files and keep links of hard linked files. FilesArchive provides means to define interdependence between files and to forward changes from dependencies to dependents. Use FilesArchive to avoid unnecessary CPU workload."
  version : "0.3.106"
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

execution :

  scripts :
    test : wtest staging
    docgen : wdocgen staging

path :

  repository : git+https://github.com/Wandalen/wFilesArchive.git
  bugs : https://github.com/Wandalen/wFilesArchive/issues

step :

  export.proto :
    inherit : export
    export : path::proto
    tar : 0
    criterion :
      debug : 1
      proto : 1

build :

  proto.export :
    criterion :
      default : 1
      debug : 1
      raw : 1
      proto : 1
      export : 1
      tar : 1
      public : 1
    steps :
      - build::debug.raw
      - step::export.proto

